export interface Translation {
  title: string;
  subtitle: string;
  galleryDescription: string;
  viewInGallery: string;
  browseGallery: string;
  whatIs: string;
  whatIsContent: string;
  statistics: string;
  totalPrompts: string;
  featuredPrompts: string;
  lastUpdated: string;
  featuredSection: string;
  allPrompts: string;
  morePrompts: string;
  morePromptsContent: string;
  prompt: string;
  tips: string;
  tipsSection: string;
  author: string;
  source: string;
  published: string;
  featured: string;
  tryItNow: string;
  contributing: string;
  contributingContent: string;
  license: string;
  licenseContent: string;
  acknowledgements: string;
  acknowledgementsContent: string;
  starHistory: string;
  madeWith: string;
  copyright: string;
  videoPreview: string;
  referenceImage: string;
  tableOfContents: string;
  copyrightNotice: string;
  // Comparison table
  featureCol: string;
  githubReadmeCol: string;
  galleryCol: string;
  videoPlayback: string;
  staticThumbnails: string;
  fullVideoPlayback: string;
  searchFeature: string;
  ctrlFOnly: string;
  fuzzySearch: string;
  mobileFeature: string;
  mobileBasic: string;
  mobileResponsive: string;
  languagesFeature: string;
  // Stats table
  metricCol: string;
  countCol: string;
  tipsAndTutorials: string;
  // Prompt list
  sortedByDate: string;
  moreNotShown: string;
  // Tips section
  tipsSubtitle: string;
  andMoreTips: string;
  viewAllInGallery: string;
  // Video
  clickToWatch: string;
  watchVideo: string;
  // Footer
  submitPrompt: string;
  starRepo: string;
  autoGenerated: string;
  // Renoise traffic CTAs
  runItCta: string;
  runItCtaLink: string;
  exploreMore: string;
  featureSeedance: string;
  guideMovieTrailer: string;
  guideMusicVideo: string;
  guidePhotoToVideo: string;
}

const en: Translation = {
  title: 'Awesome Seedance 2.5 Video Prompts',
  subtitle: '**Official Seedance 2.5 preview prompts from ByteDance / Volcano Ark** — an official preview/sample set, **NOT** community-contributed. Seedance 2.5 is still rolling out and **not yet generally available**; community-submitted prompts will be added after general availability.',
  galleryDescription: 'Browse all prompts with video previews, search, and one-click generation',
  viewInGallery: 'View in Web Gallery',
  browseGallery: 'Browse all Seedance 2.5 prompts on Renoise',
  whatIs: 'What is Seedance 2.5?',
  whatIsContent: `**Seedance 2.5** is the next-generation video generation model from **ByteDance**, available via **Volcano Ark (火山方舟)**. The prompts in this repository are an **official preview/sample set** published by ByteDance / Volcano Ark to showcase Seedance 2.5's capabilities.

> ⚠️ **Seedance 2.5 is still rolling out and not yet generally available.** These are official preview prompts, **not community contributions**. Community-submitted prompts will be added here after general availability.

**Highlights showcased in this preview:**

* 🎬 **Native long-form generation** — extended single-shot durations
* 🖼️ **Multi-reference input** — many reference images per generation
* 📐 **Up to 4K resolution**
* 🔊 **Auto dubbing & scoring** — automatic voiceover and background music
* 🎨 **Creative text animation, UGC, and product showcases**`,
  statistics: '📊 Statistics',
  totalPrompts: 'Total Prompts',
  featuredPrompts: 'Featured',
  lastUpdated: 'Last Updated',
  featuredSection: '⭐ Featured Prompts',
  allPrompts: '🎬 All Prompts',
  morePrompts: '📚 More Prompts',
  morePromptsContent: 'This README shows the latest prompts. Visit our gallery for the full collection with video previews and search.',
  prompt: 'Prompt',
  tips: 'Tips',
  tipsSection: '💡 Usage Tips',
  author: 'Author',
  source: 'Source',
  published: 'Published',
  featured: '⭐ Featured',
  tryItNow: '👉 Try it now →',
  contributing: '🤝 Contributing',
  contributingContent: 'This repository currently hosts the **official Seedance 2.5 preview set**. Community prompt submissions will open after Seedance 2.5 reaches general availability — see our [Contributing Guide](CONTRIBUTING.md).',
  license: '📄 License',
  licenseContent: 'This collection is licensed under [CC BY 4.0](LICENSE). You are free to share and adapt the prompts with attribution.',
  acknowledgements: '🙏 Acknowledgements',
  acknowledgementsContent: 'These preview prompts are published by **ByteDance / Volcano Ark (火山方舟)** as the official Seedance 2.5 sample set. Thanks to the Seedance team for sharing them.',
  starHistory: '⭐ Star History',
  madeWith: 'Made with ❤️ by',
  copyright: '© 2026 Renoise. All rights reserved.',
  videoPreview: 'Video Preview',
  referenceImage: 'Reference Image',
  tableOfContents: 'Table of Contents',
  copyrightNotice: 'Notice: These are official Seedance 2.5 preview prompts from ByteDance / Volcano Ark, shared for educational and demonstration purposes. If you believe any content infringes on your rights, please open an issue and we will remove it promptly.',
  featureCol: 'Feature',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Gallery',
  videoPlayback: 'Video Playback',
  staticThumbnails: 'Static thumbnails',
  fullVideoPlayback: 'Full video playback',
  searchFeature: 'Search',
  ctrlFOnly: 'Ctrl+F only',
  fuzzySearch: 'Multi-field fuzzy search',
  mobileFeature: 'Mobile',
  mobileBasic: 'Basic',
  mobileResponsive: 'Fully responsive',
  languagesFeature: 'Languages',
  metricCol: 'Metric',
  countCol: 'Count',
  tipsAndTutorials: 'Tips & Tutorials',
  sortedByDate: 'Sorted by publish date (newest first)',
  moreNotShown: 'more prompts not shown here',
  tipsSubtitle: 'Tips for getting the most out of Seedance 2.5',
  andMoreTips: 'and {n} more tips.',
  viewAllInGallery: 'View all in Gallery',
  clickToWatch: 'Click image to watch video',
  watchVideo: 'Watch Video',
  submitPrompt: 'Submit a Prompt',
  starRepo: 'Star this repo',
  autoGenerated: 'This README is automatically generated. Last updated:',
  runItCta: '💡 **Copy any prompt and {link}** — no setup, no install.',
  runItCtaLink: 'run it instantly in Renoise →',
  exploreMore: '🚀 Explore more on Renoise',
  featureSeedance: 'Seedance 2.5 model',
  guideMovieTrailer: 'AI Movie Trailer',
  guideMusicVideo: 'AI Music Video',
  guidePhotoToVideo: 'AI Photo to Video',
};

const zhCN: Translation = {
  title: 'Awesome Seedance 2.5 视频提示词',
  subtitle: '**来自 ByteDance / 火山方舟（Volcano Ark）的 Seedance 2.5 官方预览提示词** —— 这是官方预览/示例集，**并非**社区贡献。Seedance 2.5 仍在灰度推出，**尚未全量开放**；社区提交的提示词将在全量开放后加入。',
  galleryDescription: '浏览所有提示词，支持视频预览、搜索和一键生成',
  viewInGallery: '🎬 在画廊中查看',
  browseGallery: '浏览画廊',
  whatIs: 'Seedance 2.5 是什么？',
  whatIsContent: `**Seedance 2.5** 是 **字节跳动** 的新一代视频生成模型，通过 **火山方舟（Volcano Ark）** 提供。本仓库中的提示词是 ByteDance / 火山方舟发布的 **官方预览/示例集**，用于展示 Seedance 2.5 的能力。

> ⚠️ **Seedance 2.5 仍在灰度推出，尚未全量开放。** 这些是官方预览提示词，**并非社区贡献**。社区提交的提示词将在全量开放后加入。

**本预览展示的亮点：**

* 🎬 **原生长视频生成** — 更长的单镜头时长
* 🖼️ **多参考图输入** — 单次生成可使用多张参考图
* 📐 **最高 4K 分辨率**
* 🔊 **自动配音配乐** — 自动生成旁白和背景音乐
* 🎨 **创意文字动画、UGC 与商品展示**`,
  statistics: '📊 统计数据',
  totalPrompts: '提示词总数',
  featuredPrompts: '精选',
  lastUpdated: '最后更新',
  featuredSection: '⭐ 精选提示词',
  allPrompts: '🎬 所有提示词',
  morePrompts: '📚 更多提示词',
  morePromptsContent: '本 README 展示了最新的提示词。访问我们的画廊查看完整合集，支持视频预览和搜索。',
  prompt: '提示词',
  tips: '使用技巧',
  tipsSection: '💡 使用技巧',
  author: '作者',
  source: '来源',
  published: '发布日期',
  featured: '⭐ 精选',
  tryItNow: '👉 立即试用 →',
  contributing: '🤝 贡献指南',
  contributingContent: '本仓库目前收录的是 **Seedance 2.5 官方预览集**。社区提示词投稿将在 Seedance 2.5 全量开放后开启 —— 详见[贡献指南](CONTRIBUTING.md)。',
  license: '📄 许可证',
  licenseContent: '本合集采用 [CC BY 4.0](LICENSE) 许可。你可以在注明出处的情况下自由分享和改编这些提示词。',
  acknowledgements: '🙏 致谢',
  acknowledgementsContent: '本预览提示词由 **ByteDance / 火山方舟（Volcano Ark）** 作为 Seedance 2.5 官方示例集发布。感谢 Seedance 团队。',
  starHistory: '⭐ Star 历史',
  madeWith: '用 ❤️ 制作',
  copyright: '© 2026 Renoise 版权所有',
  videoPreview: '视频预览',
  referenceImage: '参考图片',
  tableOfContents: '目录',
  copyrightNotice: '声明：这些是来自 ByteDance / 火山方舟的 Seedance 2.5 官方预览提示词，仅用于学习和演示目的。如果您认为任何内容侵犯了您的权利，请提交 Issue，我们将及时删除。',
  featureCol: '功能',
  githubReadmeCol: 'GitHub README',
  galleryCol: '在线画廊',
  videoPlayback: '视频播放',
  staticThumbnails: '静态缩略图',
  fullVideoPlayback: '完整视频播放',
  searchFeature: '搜索',
  ctrlFOnly: '仅 Ctrl+F',
  fuzzySearch: '多字段模糊搜索',
  mobileFeature: '移动端',
  mobileBasic: '基础',
  mobileResponsive: '完全响应式',
  languagesFeature: '多语言',
  metricCol: '指标',
  countCol: '数量',
  tipsAndTutorials: '技巧 & 教程',
  sortedByDate: '按发布日期排序（最新优先）',
  moreNotShown: '条提示词未在此显示',
  tipsSubtitle: 'Seedance 2.5 使用技巧',
  andMoreTips: '以及另外 {n} 条技巧。',
  viewAllInGallery: '在画廊中查看全部',
  clickToWatch: '点击图片观看视频',
  watchVideo: '观看视频',
  submitPrompt: '提交提示词',
  starRepo: '点个 Star',
  autoGenerated: '本 README 由脚本自动生成。最后更新：',
  runItCta: '💡 **复制任意提示词，{link}** — 无需安装、无需配置。',
  runItCtaLink: '在 Renoise 里一键生成 →',
  exploreMore: '🚀 在 Renoise 探索更多',
  featureSeedance: 'Seedance 2.5 模型',
  guideMovieTrailer: 'AI 电影预告片',
  guideMusicVideo: 'AI 音乐视频',
  guidePhotoToVideo: 'AI 图片转视频',
};

const ja: Translation = {
  title: 'Awesome Seedance 2.5 動画プロンプト',
  subtitle: '**ByteDance / 火山方舟（Volcano Ark）による Seedance 2.5 公式プレビュープロンプト** — これは公式のプレビュー/サンプル集であり、**コミュニティ投稿ではありません**。Seedance 2.5 は段階的に展開中で、**まだ一般提供されていません**。コミュニティ投稿のプロンプトは一般提供開始後に追加されます。',
  galleryDescription: 'すべてのプロンプトを動画プレビュー・検索・ワンクリック生成で閲覧',
  viewInGallery: '🎬 ウェブギャラリーで閲覧',
  browseGallery: 'Renoise でプロンプトを閲覧',
  whatIs: 'Seedance 2.5 とは？',
  whatIsContent: `**Seedance 2.5** は **ByteDance** の次世代動画生成モデルで、**火山方舟（Volcano Ark）** 経由で利用できます。このリポジトリのプロンプトは、Seedance 2.5 の機能を紹介するために ByteDance / 火山方舟 が公開した **公式プレビュー/サンプル集** です。

> ⚠️ **Seedance 2.5 は段階的に展開中で、まだ一般提供されていません。** これらは公式プレビュープロンプトであり、**コミュニティ投稿ではありません**。コミュニティ投稿のプロンプトは一般提供開始後に追加されます。

**このプレビューで紹介される特徴：**

* 🎬 **ネイティブ長尺生成** — より長い単一ショット
* 🖼️ **複数参照入力** — 1回の生成で多数の参照画像
* 📐 **最大4K解像度**
* 🔊 **自動吹替・BGM** — 自動ナレーション・BGM生成
* 🎨 **クリエイティブなテキストアニメーション・UGC・商品紹介**`,
  statistics: '📊 統計',
  totalPrompts: 'プロンプト総数',
  featuredPrompts: '注目',
  lastUpdated: '最終更新',
  featuredSection: '⭐ 注目プロンプト',
  allPrompts: '🎬 全プロンプト',
  morePrompts: '📚 さらに多くのプロンプト',
  morePromptsContent: 'この README には最新のプロンプトを掲載しています。動画プレビューと検索付きの完全なコレクションはギャラリーをご覧ください。',
  prompt: 'プロンプト',
  tips: '使い方のコツ',
  tipsSection: '💡 使い方のコツ',
  author: '作者',
  source: 'ソース',
  published: '公開日',
  featured: '⭐ 注目',
  tryItNow: '👉 今すぐ試す →',
  contributing: '🤝 コントリビュート',
  contributingContent: 'このリポジトリには現在 **Seedance 2.5 公式プレビューセット** を掲載しています。コミュニティからのプロンプト投稿は、Seedance 2.5 の一般提供開始後に受付を開始します —— [コントリビュートガイド](CONTRIBUTING.md)をご覧ください。',
  license: '📄 ライセンス',
  licenseContent: 'このコレクションは [CC BY 4.0](LICENSE) ライセンスの下で公開されています。帰属表示のもと、自由に共有・改変できます。',
  acknowledgements: '🙏 謝辞',
  acknowledgementsContent: 'このプレビュープロンプトは、Seedance 2.5 の公式サンプル集として **ByteDance / 火山方舟（Volcano Ark）** が公開しています。Seedance チームに感謝します。',
  starHistory: '⭐ Star 履歴',
  madeWith: '❤️ で制作',
  copyright: '© 2026 Renoise. All rights reserved.',
  videoPreview: '動画プレビュー',
  referenceImage: '参考画像',
  tableOfContents: '目次',
  copyrightNotice: 'お知らせ：これらは ByteDance / 火山方舟による Seedance 2.5 公式プレビュープロンプトで、教育・デモ目的で共有されています。権利侵害に該当するコンテンツがある場合は、Issue を作成してください。速やかに対応いたします。',
  featureCol: '機能',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'ギャラリー',
  videoPlayback: '動画再生',
  staticThumbnails: '静止サムネイル',
  fullVideoPlayback: '完全な動画再生',
  searchFeature: '検索',
  ctrlFOnly: 'Ctrl+F のみ',
  fuzzySearch: '複数フィールドのあいまい検索',
  mobileFeature: 'モバイル',
  mobileBasic: '基本対応',
  mobileResponsive: '完全レスポンシブ',
  languagesFeature: '言語',
  metricCol: '指標',
  countCol: '数',
  tipsAndTutorials: 'ヒント & チュートリアル',
  sortedByDate: '公開日順（新しい順）',
  moreNotShown: '件のプロンプトが非表示',
  tipsSubtitle: 'Seedance 2.5 を最大限に活用するためのヒント',
  andMoreTips: 'その他 {n} 件のヒント。',
  viewAllInGallery: 'ギャラリーですべて表示',
  clickToWatch: '画像をクリックして動画を再生',
  watchVideo: '動画を見る',
  submitPrompt: 'プロンプトを提出',
  starRepo: 'Star する',
  autoGenerated: 'この README は自動生成されています。最終更新：',
  runItCta: '💡 **プロンプトをコピーして{link}** — セットアップ・インストール不要。',
  runItCtaLink: 'Renoise ですぐに生成 →',
  exploreMore: '🚀 Renoise でもっと見る',
  featureSeedance: 'Seedance 2.5 モデル',
  guideMovieTrailer: 'AI 映画予告編',
  guideMusicVideo: 'AI ミュージックビデオ',
  guidePhotoToVideo: 'AI 写真から動画',
};

const ptBR: Translation = {
  title: 'Awesome Seedance 2.5 Prompts de Vídeo',
  subtitle: '**Prompts oficiais de preview do Seedance 2.5 da ByteDance / Volcano Ark** — um conjunto oficial de preview/amostra, e **NÃO** contribuído pela comunidade. O Seedance 2.5 ainda está em lançamento gradual e **ainda não está disponível para todos**; prompts enviados pela comunidade serão adicionados após a disponibilidade geral.',
  galleryDescription: 'Navegue por todos os prompts com prévias de vídeo, busca e geração com um clique',
  viewInGallery: '🎬 Ver na Galeria Web',
  browseGallery: 'Ver todos os prompts Seedance 2.5 no Renoise',
  whatIs: 'O que é o Seedance 2.5?',
  whatIsContent: `**Seedance 2.5** é o modelo de geração de vídeo de próxima geração da **ByteDance**, disponível via **Volcano Ark (火山方舟)**. Os prompts neste repositório são um **conjunto oficial de preview/amostra** publicado pela ByteDance / Volcano Ark para demonstrar os recursos do Seedance 2.5.

> ⚠️ **O Seedance 2.5 ainda está em lançamento gradual e ainda não está disponível para todos.** Estes são prompts oficiais de preview, **não contribuições da comunidade**. Prompts enviados pela comunidade serão adicionados aqui após a disponibilidade geral.

**Destaques apresentados neste preview:**

* 🎬 **Geração nativa de formato longo** — durações estendidas em plano único
* 🖼️ **Entrada com múltiplas referências** — várias imagens de referência por geração
* 📐 **Resolução até 4K**
* 🔊 **Dublagem e trilha automáticas** — narração e música de fundo automáticas
* 🎨 **Animação de texto criativa, UGC e vitrines de produtos**`,
  statistics: '📊 Estatísticas',
  totalPrompts: 'Total de Prompts',
  featuredPrompts: 'Destaques',
  lastUpdated: 'Última Atualização',
  featuredSection: '⭐ Prompts em Destaque',
  allPrompts: '🎬 Todos os Prompts',
  morePrompts: '📚 Mais Prompts',
  morePromptsContent: 'Este README mostra os prompts mais recentes. Visite nossa galeria para a coleção completa com prévias de vídeo e busca.',
  prompt: 'Prompt',
  tips: 'Dicas',
  tipsSection: '💡 Dicas de Uso',
  author: 'Autor',
  source: 'Fonte',
  published: 'Publicado',
  featured: '⭐ Destaque',
  tryItNow: '👉 Experimente agora →',
  contributing: '🤝 Contribuições',
  contributingContent: 'Este repositório hospeda atualmente o **conjunto oficial de preview do Seedance 2.5**. O envio de prompts pela comunidade será aberto após o Seedance 2.5 atingir disponibilidade geral — consulte nosso [Guia de Contribuição](CONTRIBUTING.md).',
  license: '📄 Licença',
  licenseContent: 'Esta coleção é licenciada sob [CC BY 4.0](LICENSE). Você pode compartilhar e adaptar os prompts livremente com atribuição.',
  acknowledgements: '🙏 Agradecimentos',
  acknowledgementsContent: 'Estes prompts de preview são publicados pela **ByteDance / Volcano Ark (火山方舟)** como o conjunto oficial de amostras do Seedance 2.5. Obrigado à equipe Seedance.',
  starHistory: '⭐ Histórico de Stars',
  madeWith: 'Feito com ❤️ por',
  copyright: '© 2026 Renoise. Todos os direitos reservados.',
  videoPreview: 'Prévia do Vídeo',
  referenceImage: 'Imagem de Referência',
  tableOfContents: 'Índice',
  copyrightNotice: 'Aviso: Estes são prompts oficiais de preview do Seedance 2.5 da ByteDance / Volcano Ark, compartilhados para fins educacionais e de demonstração. Se você acredita que algum conteúdo infringe seus direitos, abra uma issue e removeremos prontamente.',
  featureCol: 'Recurso',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Galeria',
  videoPlayback: 'Reprodução de Vídeo',
  staticThumbnails: 'Miniaturas estáticas',
  fullVideoPlayback: 'Reprodução completa de vídeo',
  searchFeature: 'Busca',
  ctrlFOnly: 'Apenas Ctrl+F',
  fuzzySearch: 'Busca fuzzy multicampo',
  mobileFeature: 'Mobile',
  mobileBasic: 'Básico',
  mobileResponsive: 'Totalmente responsivo',
  languagesFeature: 'Idiomas',
  metricCol: 'Métrica',
  countCol: 'Quantidade',
  tipsAndTutorials: 'Dicas & Tutoriais',
  sortedByDate: 'Ordenado por data de publicação (mais recente primeiro)',
  moreNotShown: 'prompts adicionais não exibidos aqui',
  tipsSubtitle: 'Dicas para aproveitar ao máximo o Seedance 2.5',
  andMoreTips: 'e mais {n} dicas.',
  viewAllInGallery: 'Ver tudo na Galeria',
  clickToWatch: 'Clique na imagem para assistir o vídeo',
  watchVideo: 'Assistir Vídeo',
  submitPrompt: 'Enviar um Prompt',
  starRepo: 'Dar Star',
  autoGenerated: 'Este README é gerado automaticamente. Última atualização:',
  runItCta: '💡 **Copie qualquer prompt e {link}** — sem instalação, sem configuração.',
  runItCtaLink: 'gere na hora no Renoise →',
  exploreMore: '🚀 Explore mais no Renoise',
  featureSeedance: 'modelo Seedance 2.5',
  guideMovieTrailer: 'Trailer de Filme com IA',
  guideMusicVideo: 'Videoclipe com IA',
  guidePhotoToVideo: 'Foto para Vídeo com IA',
};

const es: Translation = {
  title: 'Awesome Seedance 2.5 Prompts de Video',
  subtitle: '**Prompts oficiales de vista previa de Seedance 2.5 de ByteDance / Volcano Ark** — un conjunto oficial de vista previa/muestra, y **NO** contribuido por la comunidad. Seedance 2.5 aún se está implementando y **todavía no está disponible para todos**; los prompts enviados por la comunidad se agregarán tras la disponibilidad general.',
  galleryDescription: 'Explora todos los prompts con vistas previas de video, búsqueda y generación con un clic',
  viewInGallery: '🎬 Ver en la Galería Web',
  browseGallery: 'Ver todos los prompts Seedance 2.5 en Renoise',
  whatIs: '¿Qué es Seedance 2.5?',
  whatIsContent: `**Seedance 2.5** es el modelo de generación de video de próxima generación de **ByteDance**, disponible a través de **Volcano Ark (火山方舟)**. Los prompts de este repositorio son un **conjunto oficial de vista previa/muestra** publicado por ByteDance / Volcano Ark para mostrar las capacidades de Seedance 2.5.

> ⚠️ **Seedance 2.5 aún se está implementando y todavía no está disponible para todos.** Estos son prompts oficiales de vista previa, **no contribuciones de la comunidad**. Los prompts enviados por la comunidad se agregarán aquí tras la disponibilidad general.

**Aspectos destacados en esta vista previa:**

* 🎬 **Generación nativa de formato largo** — duraciones extendidas en una sola toma
* 🖼️ **Entrada de múltiples referencias** — varias imágenes de referencia por generación
* 📐 **Resolución hasta 4K**
* 🔊 **Doblaje y música automáticos** — narración y música de fondo automáticas
* 🎨 **Animación de texto creativa, UGC y vitrinas de productos**`,
  statistics: '📊 Estadísticas',
  totalPrompts: 'Total de Prompts',
  featuredPrompts: 'Destacados',
  lastUpdated: 'Última Actualización',
  featuredSection: '⭐ Prompts Destacados',
  allPrompts: '🎬 Todos los Prompts',
  morePrompts: '📚 Más Prompts',
  morePromptsContent: 'Este README muestra los prompts más recientes. Visita nuestra galería para la colección completa con vistas previas de video y búsqueda.',
  prompt: 'Prompt',
  tips: 'Consejos',
  tipsSection: '💡 Consejos de Uso',
  author: 'Autor',
  source: 'Fuente',
  published: 'Publicado',
  featured: '⭐ Destacado',
  tryItNow: '👉 Pruébalo ahora →',
  contributing: '🤝 Contribuciones',
  contributingContent: 'Este repositorio aloja actualmente el **conjunto oficial de vista previa de Seedance 2.5**. El envío de prompts por parte de la comunidad se abrirá tras la disponibilidad general de Seedance 2.5 — consulta nuestra [Guía de Contribución](CONTRIBUTING.md).',
  license: '📄 Licencia',
  licenseContent: 'Esta colección está licenciada bajo [CC BY 4.0](LICENSE). Puedes compartir y adaptar los prompts libremente con atribución.',
  acknowledgements: '🙏 Agradecimientos',
  acknowledgementsContent: 'Estos prompts de vista previa son publicados por **ByteDance / Volcano Ark (火山方舟)** como el conjunto oficial de muestras de Seedance 2.5. Gracias al equipo de Seedance.',
  starHistory: '⭐ Historial de Stars',
  madeWith: 'Hecho con ❤️ por',
  copyright: '© 2026 Renoise. Todos los derechos reservados.',
  videoPreview: 'Vista Previa del Video',
  referenceImage: 'Imagen de Referencia',
  tableOfContents: 'Índice',
  copyrightNotice: 'Aviso: Estos son prompts oficiales de vista previa de Seedance 2.5 de ByteDance / Volcano Ark, compartidos con fines educativos y de demostración. Si cree que algún contenido infringe sus derechos, abra un issue y lo eliminaremos de inmediato.',
  featureCol: 'Característica',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Galería',
  videoPlayback: 'Reproducción de Video',
  staticThumbnails: 'Miniaturas estáticas',
  fullVideoPlayback: 'Reproducción completa de video',
  searchFeature: 'Búsqueda',
  ctrlFOnly: 'Solo Ctrl+F',
  fuzzySearch: 'Búsqueda difusa multicampo',
  mobileFeature: 'Móvil',
  mobileBasic: 'Básico',
  mobileResponsive: 'Totalmente responsivo',
  languagesFeature: 'Idiomas',
  metricCol: 'Métrica',
  countCol: 'Cantidad',
  tipsAndTutorials: 'Consejos & Tutoriales',
  sortedByDate: 'Ordenado por fecha de publicación (más reciente primero)',
  moreNotShown: 'prompts adicionales no mostrados aquí',
  tipsSubtitle: 'Consejos para sacar el máximo provecho de Seedance 2.5',
  andMoreTips: 'y {n} consejos más.',
  viewAllInGallery: 'Ver todo en la Galería',
  clickToWatch: 'Haz clic en la imagen para ver el video',
  watchVideo: 'Ver Video',
  submitPrompt: 'Enviar un Prompt',
  starRepo: 'Dar Star',
  autoGenerated: 'Este README se genera automáticamente. Última actualización:',
  runItCta: '💡 **Copia cualquier prompt y {link}** — sin instalación ni configuración.',
  runItCtaLink: 'genéralo al instante en Renoise →',
  exploreMore: '🚀 Explora más en Renoise',
  featureSeedance: 'modelo Seedance 2.5',
  guideMovieTrailer: 'Tráiler de Película con IA',
  guideMusicVideo: 'Videoclip con IA',
  guidePhotoToVideo: 'Foto a Video con IA',
};

const I18N: Record<string, Translation> = {
  'en': en,
  'zh-CN': zhCN,
  'ja': ja,
  'pt-BR': ptBR,
  'es': es,
};

export function t(key: keyof Translation, locale: string): string {
  const lang = I18N[locale] || I18N['en'];
  return lang[key] || en[key] || key;
}

const DATE_LOCALES: Record<string, string> = {
  'en': 'en-US',
  'zh-CN': 'zh-CN',
  'ja': 'ja-JP',
  'pt-BR': 'pt-BR',
  'es': 'es-ES',
};

export function formatDateLocalized(iso: string | undefined, locale: string): string {
  if (!iso) return 'N/A';
  const dateLocale = DATE_LOCALES[locale] || 'en-US';
  return new Date(iso).toLocaleDateString(dateLocale, {
    year: 'numeric', month: 'short', day: 'numeric',
  });
}
